# Generated by Django 3.1.7 on 2021-03-09 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_item_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='owner',
            new_name='user',
        ),
    ]
